<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE GKkanji [
<!ELEMENT GKkanji (kanji_entry*)>
<!--                                                                   -->
<!ELEMENT kanji_entry (ent_seq, name, kanji, jlpt, level,  onyomi+, kunyomi+, description+ )>
	<!-- Kanji Entries consist of ...
	-->
<!ELEMENT ent_seq (#PCDATA)>
	<!-- A unique numeric sequence number for each grammar entry
	-->
<!ELEMENT name (#PCDATA)>
	<!-- A unique name identifying the title of the Grammar Pattern -->

<!ELEMENT kanji (#PCDATA)>
	<!-- The actual Kanji character -->

<!ELEMENT jlpt (#PCDATA)>
	<!--  JLPT Level N5, N4, N3, N2, N1, N1+ -->

<!ELEMENT level (#PCDATA)>
	<!--  Sublevel within the JLPT level -->

<!ELEMENT onyomi (#PCDATA)>
	<!-- A onyomi reading entry -->

<!ELEMENT kunyomi (#PCDATA)>
	<!-- A kunyomi reading entry -->

<!ELEMENT description (#PCDATA)>
	<!-- A description of the Kanji Entry ( the meaning )
	-->
]>


<!-- GKgrammar created: 2017-10-27 -->
<GKkanji>
<kanji_entry>
<ent_seq>88990000</ent_seq>
<kanji>日</kanji>
<name>日</name>
<jlpt>5</jlpt>
<level>1</level>
<onyomi>ニチ</onyomi>
<onyomi>ジツ-</onyomi>
<kunyomi>ひ</kunyomi>
<kunyomi>-び</kunyomi>	
<description>day</description>
<description>sun</description>
<description>Japan</description>
</kanji_entry>
<kanji_entry>
<ent_seq>88990001</ent_seq>
<kanji>一</kanji>
<name>一</name>
<jlpt>5</jlpt>
<level>1</level>
<onyomi>イチ</onyomi>
<onyomi>イツ</onyomi>
<onyomi>ヒト</onyomi>
<kunyomi>ひと-</kunyomi>
<description>one</description>
</kanji_entry>
<kanji_entry>
<ent_seq>88990002</ent_seq>
<kanji>国</kanji>
<name>国</name>
<jlpt>5</jlpt>
<level>1</level>
<onyomi>コク</onyomi>
<onyomi>ク</onyomi>
<description>country</description>
</kanji_entry>
<kanji_entry>
<ent_seq>88990003</ent_seq>
<kanji>人</kanji>
<name>人</name>
<jlpt>5</jlpt>
<level>1</level>
<onyomi>ジン</onyomi>
<onyomi>ニン-</onyomi>	
<kunyomi>ひと</kunyomi>
<kunyomi>-り</kunyomi>
<description>person</description>
</kanji_entry>
<kanji_entry>
<ent_seq>88990004</ent_seq>
<kanji>年</kanji>
<name>年</name>
<jlpt>5</jlpt>
<level>1</level>
<onyomi>ネン</onyomi>
<onyomi>ト</onyomi>
<description>year</description>
</kanji_entry>
<kanji_entry>
<ent_seq>88990005</ent_seq>
<kanji>大</kanji>
<name>大</name>
<jlpt>5</jlpt>
<level>1</level>
<onyomi>ダイ</onyomi>
<onyomi>タイ</onyomi>
<onyomi>-オオ.イ</onyomi>	
<kunyomi>おお-</kunyomi>
<kunyomi>おお.きい</kunyomi>	
<description>large</description>
<description>big</description>
</kanji_entry>
<kanji_entry>
<ent_seq>88990006</ent_seq>
<kanji>十</kanji>
<name>十</name>
<jlpt>5</jlpt>
<level>1</level>
<onyomi>ジュウ</onyomi>
<onyomi>ジッ</onyomi>
<onyomi>ジュッ</onyomi>
<kunyomi>とお</kunyomi>	
<description>ten</description>
</kanji_entry>
<kanji_entry>
<ent_seq>88990007</ent_seq>
<kanji>二</kanji>
<name>二</name>
<jlpt>5</jlpt>
<level>1</level>
<onyomi>ニ</onyomi>
<onyomi>ジ</onyomi>
<onyomi>フタタ.</onyomi>
<kunyomi>ふた</kunyomi>
<kunyomi>ふた.つ</kunyomi>	
<description>two</description>
</kanji_entry>
<kanji_entry>
<ent_seq>88990008</ent_seq>
<kanji>本</kanji>
<name>本</name>
<jlpt>5</jlpt>
<level>1</level>
<onyomi>ホン</onyomi>
<onyomi>モ</onyomi>
<description>book</description>
<description>present</description>
<description>main</description>
<description>true</description>
<description>real</description>
<description>counter for long things</description>
</kanji_entry>
<kanji_entry>
<ent_seq>88990009</ent_seq>
<kanji>中</kanji>
<name>中</name>
<jlpt>5</jlpt>
<level>1</level>
<onyomi>チュウ</onyomi>
<onyomi>アタ.</onyomi>
<kunyomi>なか</kunyomi>
<kunyomi>うち</kunyomi>
<description>in</description>
<description>inside</description>
<description>middle</description>
<description>mean</description>
<description>center</description>
</kanji_entry>
<kanji_entry>
<ent_seq>88990010</ent_seq>
<kanji>長</kanji>
<name>長</name>
<jlpt>5</jlpt>
<level>1</level>
<onyomi>チョウ</onyomi>
<onyomi>オ</onyomi>
<kunyomi>なが.い</kunyomi>	
<description>long</description>
<description>leader</description>
</kanji_entry>
<kanji_entry>
<ent_seq>88990011</ent_seq>
<kanji>出</kanji>
<name>出</name>
<jlpt>5</jlpt>
<level>1</level>
<onyomi>シュツ</onyomi>
<onyomi>スイ</onyomi>
<onyomi>イ.ダ</onyomi>
<kunyomi>で.る</kunyomi>
<kunyomi>nyomi>-で</kunyomi>
<kunyomi>mi>だ.す</kunyomi>
<kunyomi>omi>-だ.す</kunyomi>
<kunyomi>い.でる</kunyomi>
<description>exit</description>
<description>leave</description>
</kanji_entry>
<kanji_entry>
<ent_seq>88990012</ent_seq>
<kanji>三</kanji>
<name>三</name>
<jlpt>5</jlpt>
<level>1</level>
<onyomi>サン</onyomi>
<onyomi>ゾウ</onyomi>
<onyomi>ミッ.</onyomi>
<kunyomi>み</kunyomi>
<kunyomi>み.つ</kunyomi>
<description>three</description>
</kanji_entry>
<kanji_entry>
<ent_seq>88990013</ent_seq>
<kanji>時</kanji>
<name>時</name>
<jlpt>5</jlpt>
<level>1</level>
<onyomi>ジ</onyomi>
<onyomi>-ド</onyomi>
<kunyomi>とき</kunyomi>
<description>time</description>
<description>hour</description>
</kanji_entry>
<kanji_entry>
<ent_seq>88990014</ent_seq>
<kanji>行</kanji>
<name>行</name>
<jlpt>5</jlpt>
<level>1</level>
<onyomi>コウ</onyomi>
<onyomi>ギョウ</onyomi>
<onyomi>アン</onyomi>
<onyomi>オコ.ナ</onyomi>
<kunyomi>い.く</kunyomi>
<kunyomi>ゆ.く</kunyomi>
<kunyomi>-ゆ.き</kunyomi>
<kunyomi>-ゆき</kunyomi>
<kunyomi>-い.き</kunyomi>
<kunyomi>-いき</kunyomi>
<kunyomi>おこな.う</kunyomi>
<description>going</description>
<description>journey</description>
</kanji_entry>
<kanji_entry>
<ent_seq>88990015</ent_seq>
<kanji>見</kanji>
<name>見</name>
<jlpt>5</jlpt>
<level>1</level>
<onyomi>ケン</onyomi>
<kunyomi>み.る</kunyomi>
<kunyomi>み.える</kunyomi>
<kunyomi>み.せる</kunyomi>
<description>see</description>
<description>hopes</description>
<description>chances</description>
<description>idea</description>
<description>opinion</description>
<description>look at</description>
<description>visible</description>
</kanji_entry>
<kanji_entry>
<ent_seq>88990016</ent_seq>
<kanji>月</kanji>
<name>月</name>
<jlpt>5</jlpt>
<level>1</level>
<onyomi>ゲツ</onyomi>
<onyomi>ガツ</onyomi>
<onyomi>ツ</onyomi>
<description>month</description>
<description>moon</description>
</kanji_entry>
<kanji_entry>
<ent_seq>88990017</ent_seq>
<kanji>後</kanji>
<name>後</name>
<jlpt>5</jlpt>
<level>1</level>
<onyomi>ゴ</onyomi>
<onyomi>コウ</onyomi>
<onyomi>オク.レ</onyomi>
<kunyomi>のち</kunyomi>
<kunyomi>うし.ろ</kunyomi>
<kunyomi>うしろ</kunyomi>
<kunyomi>あと</kunyomi>
<description>behind</description>
<description>back</description>
<description>later</description>
</kanji_entry>
<kanji_entry>
<ent_seq>88990018</ent_seq>
<kanji>前</kanji>
<name>前</name>
<jlpt>5</jlpt>
<level>1</level>
<onyomi>ゼン</onyomi>
<onyomi>-マ</onyomi>
<kunyomi>まえ</kunyomi>
<description>in front</description>
<description>before</description>
</kanji_entry>
<kanji_entry>
<ent_seq>88990019</ent_seq>
<kanji>生</kanji>
<name>生</name>
<jlpt>5</jlpt>
<level>1</level>
<onyomi>セイ</onyomi>
<onyomi>ショウ-	</onyomi>
<kunyomi>い.きる</kunyomi>
<kunyomi>い.かす</kunyomi>
<kunyomi>い.ける</kunyomi>
<kunyomi>う.まれる</kunyomi>
<kunyomi>う.まれ</kunyomi>
<kunyomi>うまれ</kunyomi>
<kunyomi>う.む</kunyomi>
<kunyomi>お.う</kunyomi>
<kunyomi>は.える</kunyomi>
<kunyomi>は.やす</kunyomi>
<kunyomi>き</kunyomi>
<kunyomi>なま</kunyomi>
<kunyomi>なま-</kunyomi>
<kunyomi>な.る</kunyomi>
<description>life</description>
<description>genuine</description>
<description>birth</description>
<description>raw</description>
</kanji_entry>
<kanji_entry>
<ent_seq>88990020</ent_seq>
<kanji>五</kanji>
<name>五</name>
<jlpt>5</jlpt>
<level>1</level>
<onyomi>ゴ</onyomi>
<onyomi>イツ.</onyomi>
<kunyomi>いつ</kunyomi>
<description>five</description>
</kanji_entry>
<kanji_entry>
<ent_seq>88990021</ent_seq>
<kanji>間</kanji>
<name>間</name>
<jlpt>5</jlpt>
<level>1</level>
<onyomi>カン</onyomi>
<onyomi>ケン</onyomi>
<kunyomi>あいだ</kunyomi>
<kunyomi>ま</kunyomi>
<kunyomi>あい</kunyomi>
<description>interval</description>
<description>space</description>
</kanji_entry>
<kanji_entry>
<ent_seq>88990022</ent_seq>
<kanji>上</kanji>
<name>上</name>
<jlpt>5</jlpt>
<level>1</level>
<onyomi>ジョウ</onyomi>
<onyomi>ショウ</onyomi>
<onyomi>シャン</onyomi>
<onyomi>ヨ.</onyomi>
<kunyomi>うえ</kunyomi>
<kunyomi>-うえ</kunyomi>
<kunyomi>うわ-</kunyomi>
<kunyomi>かみ</kunyomi>
<kunyomi>あ.げる</kunyomi>
<kunyomi>-あ.げる</kunyomi>
<kunyomi>あ.がる</kunyomi>
<kunyomi>-あ.がる</kunyomi>
<kunyomi>あ.がり</kunyomi>
<kunyomi>-あ.がり</kunyomi>
<kunyomi>のぼ.る</kunyomi>
<kunyomi>のぼ.り</kunyomi>
<kunyomi>のぼ.</kunyomi>
<description>above</description>
<description>up</description>
</kanji_entry>
<kanji_entry>
<ent_seq>88990023</ent_seq>
<kanji>東</kanji>
<name>東</name>
<jlpt>5</jlpt>
<level>1</level>
<onyomi>トウ</onyomi>
<onyomi>ヒガ</onyomi>
<description>east</description>
</kanji_entry>
<kanji_entry>
<ent_seq>88990024</ent_seq>
<kanji>四</kanji>
<name>四</name>
<jlpt>5</jlpt>
<level>1</level>
<onyomi>シ</onyomi>
<onyomi>ヨ</onyomi>
<kunyomi>よ</kunyomi>
<kunyomi>よ.つ</kunyomi>
<kunyomi>よっ.つ</kunyomi>
<description>four</description>
</kanji_entry>
<kanji_entry>
<ent_seq>88990025</ent_seq>
<kanji>今</kanji>
<name>今</name>
<jlpt>5</jlpt>
<level>1</level>
<onyomi>コン</onyomi>
<onyomi>キン</onyomi>
<onyomi>イ</onyomi>
<description>now</description>
</kanji_entry>
<kanji_entry>
<ent_seq>88990026</ent_seq>
<kanji>金</kanji>
<name>金</name>
<jlpt>5</jlpt>
<level>1</level>
<onyomi>キン</onyomi>
<onyomi>コン</onyomi>
<onyomi>ゴン</onyomi>
<onyomi>-ガ</onyomi>
<kunyomi>かね</kunyomi>
<kunyomi>かな-</kunyomi>
<description>gold</description>
</kanji_entry>
<kanji_entry>
<ent_seq>88990027</ent_seq>
<kanji>九</kanji>
<name>九</name>
<jlpt>5</jlpt>
<level>1</level>
<onyomi>キュウ</onyomi>
<onyomi>ク</onyomi>
<onyomi>ココノ.</onyomi>
<kunyomi>ここの</kunyomi>
<description>nine</description>
</kanji_entry>
<kanji_entry>
<ent_seq>88990028</ent_seq>
<kanji>入</kanji>
<name>入</name>
<jlpt>5</jlpt>
<level>1</level>
<onyomi>ニュウ</onyomi>
<onyomi>ジュ</onyomi>
<onyomi>ハイ.</onyomi>
<kunyomi>い.る</kunyomi>
<kunyomi>-い.る</kunyomi>
<kunyomi>-い.り</kunyomi>
<kunyomi>い.れる</kunyomi>
<kunyomi>-い.れ</kunyomi>
<description>enter</description>
<description>insert</description>
</kanji_entry>
<kanji_entry>
<ent_seq>88990029</ent_seq>
<kanji>学</kanji>
<name>学</name>
<jlpt>5</jlpt>
<level>1</level>
<onyomi>ガク</onyomi>
<onyomi>マナ.</onyomi>
<description>study</description>
<description>learning</description>
<description>science</description>
</kanji_entry>
<kanji_entry>
<ent_seq>88990030</ent_seq>
<kanji>高</kanji>
<name>高</name>
<jlpt>5</jlpt>
<level>1</level>
<onyomi>コウ</onyomi>
<onyomi>タカ.メ</onyomi>
<kunyomi>たか.い</kunyomi>
<kunyomi>たか</kunyomi>
<kunyomi>-だか</kunyomi>
<kunyomi>たか.まる</kunyomi>
<description>tall</description>
<description>high</description>
<description>expensive</description>
</kanji_entry>
<kanji_entry>
<ent_seq>88990031</ent_seq>
<kanji>円</kanji>
<name>円</name>
<jlpt>5</jlpt>
<level>1</level>
<onyomi>エン</onyomi>
<onyomi>マロ.ヤ</onyomi>	
<kunyomi>まる.い</kunyomi>
<kunyomi>まる</kunyomi>
<kunyomi>まど</kunyomi>
<kunyomi>まど.か	</kunyomi>
<description>circle</description>
<description>yen</description>
<description>round</description>
</kanji_entry>
<kanji_entry>
<ent_seq>88990032</ent_seq>
<kanji>子</kanji>
<name>子</name>
<jlpt>5</jlpt>
<level>1</level>
<onyomi>シ</onyomi>
<onyomi>ス</onyomi>
<onyomi>ツ</onyomi>
<kunyomi>こ</kunyomi>
<kunyomi>-こ</kunyomi>
<description>child</description>
<description>sign of the rat</description>
<description>11PM-1AM</description>
<description>first sign of Chinese zodiac</description>
</kanji_entry>
<kanji_entry>
<ent_seq>88990033</ent_seq>
<kanji>外</kanji>
<name>外</name>
<jlpt>5</jlpt>
<level>1</level>
<onyomi>ガイ</onyomi>
<onyomi>ゲ</onyomi>
<kunyomi>そと</kunyomi>
<kunyomi>ほか</kunyomi>
<kunyomi>はず.す</kunyomi>
<kunyomi>はず.れる</kunyomi>
<kunyomi>と</kunyomi>
<description>outside</description>
</kanji_entry>
<kanji_entry>
<ent_seq>88990034</ent_seq>
<kanji>八</kanji>
<name>八</name>
<jlpt>5</jlpt>
<level>1</level>
<onyomi>ハチ</onyomi>
<onyomi>ヨ</onyomi>
<kunyomi>や</kunyomi>
<kunyomi>や.つ</kunyomi>
<kunyomi>やっ.つ</kunyomi>
<description>eight</description>
</kanji_entry>
<kanji_entry>
<ent_seq>88990035</ent_seq>
<kanji>六</kanji>
<name>六</name>
<jlpt>5</jlpt>
<level>1</level>
<onyomi>ロク</onyomi>
<onyomi>リク</onyomi>
<onyomi>ム</onyomi>
<kunyomi>む</kunyomi>
<kunyomi>む.つ</kunyomi>
<kunyomi>むっ.つ</kunyomi>
<description>six</description>
</kanji_entry>
<kanji_entry>
<ent_seq>88990036</ent_seq>
<kanji>下</kanji>
<name>下</name>
<jlpt>5</jlpt>
<level>1</level>
<onyomi>カ</onyomi>
<onyomi>ゲ</onyomi>
<onyomi>オ.リ</onyomi>
<kunyomi>した</kunyomi>
<kunyomi>しも</kunyomi>
<kunyomi>もと</kunyomi>
<kunyomi>さ.げる</kunyomi>
<kunyomi>さ.がる</kunyomi>
<kunyomi>くだ.る</kunyomi>
<kunyomi>くだ.り</kunyomi>
<kunyomi>くだ.す</kunyomi>
<kunyomi>-くだ.す</kunyomi>
<kunyomi>くだ.さる</kunyomi>
<kunyomi>お.ろす</kunyomi>
<description>below</description>
<description>down</description>
<description>descend</description>
<description>give</description>
<description>low</description>
<description>inferior</description>
</kanji_entry>
<kanji_entry>
<ent_seq>88990037</ent_seq>
<kanji>来</kanji>
<name>来</name>
<jlpt>5</jlpt>
<level>1</level>
<onyomi>ライ</onyomi>
<onyomi>タイ</onyomi>
<kunyomi>く.る</kunyomi>
<kunyomi>きた.る</kunyomi>
<kunyomi>きた.す</kunyomi>
<kunyomi>き.たす</kunyomi>
<kunyomi>き.たる</kunyomi>
<kunyomi>き</kunyomi>
<description>come</description>
<description>due</description>
<description>next</description>
<description>cause</description>
<description>become</description>
</kanji_entry>
<kanji_entry>
<ent_seq>88990038</ent_seq>
<kanji>気</kanji>
<name>気</name>
<jlpt>5</jlpt>
<level>1</level>
<onyomi>キ</onyomi>
<onyomi>ケ</onyomi>
<kunyomi>いき</kunyomi>
<description>spirit</description>
<description>mind</description>
</kanji_entry>
<kanji_entry>
<ent_seq>88990039</ent_seq>
<kanji>小</kanji>
<name>小</name>
<jlpt>5</jlpt>
<level>1</level>
<onyomi>ショウ</onyomi>
<kunyomi>ちい.さい</kunyomi>
<kunyomi>こ-</kunyomi>
<kunyomi>お-</kunyomi>
<kunyomi>さ</kunyomi>
<description>little</description>
<description>small</description>
</kanji_entry>
<kanji_entry>
<ent_seq>88990040</ent_seq>
<kanji>七</kanji>
<name>七</name>
<jlpt>5</jlpt>
<level>1</level>
<onyomi>シチ</onyomi>
<onyomi>ナ</onyomi>
<kunyomi>なな</kunyomi>
<kunyomi>なな.つ</kunyomi>
<description>seven</description>
</kanji_entry>
<kanji_entry>
<ent_seq>88990041</ent_seq>
<kanji>山</kanji>
<name>山</name>
<jlpt>5</jlpt>
<level>1</level>
<onyomi>サン</onyomi>
<onyomi>セン</onyomi>
<onyomi>ヤ</onyomi>
<description>mountain</description>
</kanji_entry>
<kanji_entry>
<ent_seq>88990042</ent_seq>
<kanji>話</kanji>
<name>話</name>
<jlpt>5</jlpt>
<level>1</level>
<onyomi>ワ</onyomi>
<kunyomi>はな.す</kunyomi>
<kunyomi>はなし</kunyomi>
<description>tale</description>
<description>talk</description>
</kanji_entry>
<kanji_entry>
<ent_seq>88990043</ent_seq>
<kanji>女</kanji>
<name>女</name>
<jlpt>5</jlpt>
<level>1</level>
<onyomi>ジョ</onyomi>
<onyomi>ニョ</onyomi>
<onyomi>ニョウ</onyomi>
<kunyomi>おんな</kunyomi>
<description>woman</description>
<description>female</description>
</kanji_entry>
<kanji_entry>
<ent_seq>88990044</ent_seq>
<kanji>北</kanji>
<name>北</name>
<jlpt>5</jlpt>
<level>1</level>
<onyomi>ホク</onyomi>
<onyomi>キ</onyomi>
<description>north</description>
</kanji_entry>
<kanji_entry>
<ent_seq>88990045</ent_seq>
<kanji>午</kanji>
<name>午</name>
<jlpt>5</jlpt>
<level>1</level>
<onyomi>ゴ</onyomi>
<kunyomi>うま</kunyomi>
<description>noon</description>
<description>sign of the horse</description>
<description>11AM-1PM</description>
<description>seventh sign of Chinese zodiac</description>
</kanji_entry>
<kanji_entry>
<ent_seq>88990046</ent_seq>
<kanji>百</kanji>
<name>百</name>
<jlpt>5</jlpt>
<level>1</level>
<onyomi>ヒャク</onyomi>
<onyomi>ビャク</onyomi>
<onyomi>モ</onyomi>
<description>hundred</description>
</kanji_entry>
<kanji_entry>
<ent_seq>88990047</ent_seq>
<kanji>書</kanji>
<name>書</name>
<jlpt>5</jlpt>
<level>1</level>
<onyomi>ショ</onyomi>
<onyomi>-ガ</onyomi>
<kunyomi>か.く</kunyomi>
<kunyomi>-が.き</kunyomi>
<description>write</description>
</kanji_entry>
<kanji_entry>
<ent_seq>88990048</ent_seq>
<kanji>先</kanji>
<name>先</name>
<jlpt>5</jlpt>
<level>1</level>
<onyomi>セン</onyomi>
<onyomi>マ.</onyomi>
<kunyomi>さき</kunyomi>
<description>before</description>
<description>ahead</description>
<description>previous</description>
<description>future</description>
<description>precedence</description>
</kanji_entry>
<kanji_entry>
<ent_seq>88990049</ent_seq>
<kanji>名</kanji>
<name>名</name>
<jlpt>5</jlpt>
<level>1</level>
<onyomi>メイ</onyomi>
<onyomi>ミョウ-	</onyomi>
<kunyomi>な</kunyomi>
<description>name</description>
<jlpt>5</jlpt>
<level>1</level>
<description>noted</description>
<description>distinguished</description>
<description>reputation</description>
</kanji_entry>
<kanji_entry>
<ent_seq>88990050</ent_seq>
<kanji>川</kanji>
<name>川</name>
<jlpt>5</jlpt>
<level>1</level>
<onyomi>セン</onyomi>
<onyomi>カ</onyomi>
<description>stream</description>
<description>river</description>
</kanji_entry>
<kanji_entry>
<ent_seq>88990051</ent_seq>
<kanji>千</kanji>
<name>千</name>
<jlpt>5</jlpt>
<level>1</level>
<onyomi>セン</onyomi>
<description>thousand</description>
</kanji_entry>
<kanji_entry>
<ent_seq>88990052</ent_seq>
<kanji>水</kanji>
<name>水</name>
<jlpt>5</jlpt>
<level>1</level>
<onyomi>スイ</onyomi>
<kunyomi>みず</kunyomi>
<description>water</description>
</kanji_entry>
<kanji_entry>
<ent_seq>88990053</ent_seq>
<kanji>半</kanji>
<name>半</name>
<jlpt>5</jlpt>
<level>1</level>
<onyomi>ハン</onyomi>
<onyomi>ナカ.</onyomi>
<description>half</description>
<description>middle</description>
<description>odd number</description>
<description>semi-</description>
<description>part-</description>
</kanji_entry>
<kanji_entry>
<ent_seq>88990054</ent_seq>
<kanji>男</kanji>
<name>男</name>
<jlpt>5</jlpt>
<level>1</level>
<onyomi>ダン</onyomi>
<onyomi>ナン</onyomi>
<kunyomi>おとこ</kunyomi>
<description>male</description>
</kanji_entry>
<kanji_entry>
<ent_seq>88990055</ent_seq>
<kanji>西</kanji>
<name>西</name>
<jlpt>5</jlpt>
<level>1</level>
<onyomi>セイ</onyomi>
<onyomi>サイ</onyomi>
<onyomi>ス</onyomi>
<onyomi>ニ</onyomi>
<description>west</description>
<description>Spain</description>
</kanji_entry>
<kanji_entry>
<ent_seq>88990056</ent_seq>
<kanji>電</kanji>
<name>電</name>
<jlpt>5</jlpt>
<level>1</level>
<onyomi>デン</onyomi>
<description>electricity</description>
<description>electric</description>
</kanji_entry>
<kanji_entry>
<ent_seq>88990057</ent_seq>
<kanji>校</kanji>
<name>校</name>
<jlpt>5</jlpt>
<level>1</level>
<onyomi>コウ</onyomi>
<onyomi>キョ</onyomi>
<description>exam</description>
<description>school</description>
<description>printing</description>
<description>proof</description>
<description>correction</description>
</kanji_entry>
<kanji_entry>
<ent_seq>88990058</ent_seq>
<kanji>語</kanji>
<name>語</name>
<jlpt>5</jlpt>
<level>1</level>
<onyomi>ゴ</onyomi>
<kunyomi>かた.る</kunyomi>
<kunyomi>かた.らう</kunyomi>
<description>word</description>
<description>speech</description>
<description>language</description>
</kanji_entry>
<kanji_entry>
<ent_seq>88990059</ent_seq>
<kanji>土</kanji>
<name>土</name>
<jlpt>5</jlpt>
<level>1</level>
<onyomi>ド</onyomi>
<onyomi>ト</onyomi>
<onyomi>ツ</onyomi>
<description>soil</description>
<description>earth</description>
<description>ground</description>
<description>Turkey</description>
</kanji_entry>
<kanji_entry>
<ent_seq>88990060</ent_seq>
<kanji>木</kanji>
<name>木</name>
<jlpt>5</jlpt>
<level>1</level>
<onyomi>ボク</onyomi>
<onyomi>モク</onyomi>
<kunyomi>き</kunyomi>
<kunyomi>こ</kunyomi>
<description>tree</description>
<description>wood</description>
</kanji_entry>
<kanji_entry>
<ent_seq>88990061</ent_seq>
<kanji>聞</kanji>
<name>聞</name>
<jlpt>5</jlpt>
<level>1</level>
<onyomi>ブン</onyomi>
<onyomi>モン</onyomi>
<kunyomi>き.く</kunyomi>
<kunyomi>き.こえる</kunyomi>
<description>hear</description>
<description>ask</description>
<description>listen</description>
</kanji_entry>
<kanji_entry>
<ent_seq>88990062</ent_seq>
<kanji>食</kanji>
<name>食</name>
<jlpt>5</jlpt>
<level>1</level>
<onyomi>ショク</onyomi>
<onyomi>ジキ</onyomi>
<onyomi>ハ.</onyomi>
<kunyomi>く.う</kunyomi>
<kunyomi>く.らう</kunyomi>
<kunyomi>た.べる</kunyomi>
<description>eat</description>
<description>food</description>
</kanji_entry>
<kanji_entry>
<ent_seq>88990063</ent_seq>
<kanji>車</kanji>
<name>車</name>
<jlpt>5</jlpt>
<level>1</level>
<onyomi>シャ</onyomi>
<onyomi>クル</onyomi>
<description>car</description>
</kanji_entry>
<kanji_entry>
<ent_seq>88990064</ent_seq>
<kanji>何</kanji>
<name>何</name>
<jlpt>5</jlpt>
<level>1</level>
<onyomi>カ</onyomi>
<kunyomi>なに</kunyomi>
<kunyomi>なん</kunyomi>
<kunyomi>なに-</kunyomi>
<kunyomi>なん</kunyomi>
<description>what</description>
</kanji_entry>
<kanji_entry>
<ent_seq>88990065</ent_seq>
<kanji>南</kanji>
<name>南</name>
<jlpt>5</jlpt>
<level>1</level>
<onyomi>ナン</onyomi>
<onyomi>ナ</onyomi>
<onyomi>ミナ</onyomi>
<description>south</description>
</kanji_entry>
<kanji_entry>
<ent_seq>88990066</ent_seq>
<kanji>万</kanji>
<name>万</name>
<jlpt>5</jlpt>
<level>1</level>
<onyomi>マン</onyomi>
<onyomi>バン</onyomi>
<onyomi>ヨロ</onyomi>
<description>ten thousand</description>
</kanji_entry>
<kanji_entry>
<ent_seq>88990067</ent_seq>
<kanji>毎</kanji>
<name>毎</name>
<jlpt>5</jlpt>
<level>1</level>
<onyomi>マイ</onyomi>
<onyomi>-ゴト.</onyomi>
<kunyomi>ごと</kunyomi>
<description>every</description>
</kanji_entry>
<kanji_entry>
<ent_seq>88990068</ent_seq>
<kanji>白</kanji>
<name>白</name>
<jlpt>5</jlpt>
<level>1</level>
<onyomi>ハク</onyomi>
<onyomi>ビャク</onyomi>
<onyomi>シロ.</onyomi>
<kunyomi>しろ</kunyomi>
<kunyomi>しら-</kunyomi>
<description>white</description>
</kanji_entry>
<kanji_entry>
<ent_seq>88990069</ent_seq>
<kanji>天</kanji>
<name>天</name>
<jlpt>5</jlpt>
<level>1</level>
<onyomi>テン</onyomi>
<kunyomi>あまつ</kunyomi>
<kunyomi>あめ</kunyomi>
<kunyomi>あま</kunyomi>
<description>heavens</description>
<description>sky</description>
<description>imperial</description>
</kanji_entry>
<kanji_entry>
<ent_seq>88990070</ent_seq>
<kanji>母</kanji>
<name>母</name>
<jlpt>5</jlpt>
<level>1</level>
<onyomi>ボ</onyomi>
<kunyomi>はは</kunyomi>
<kunyomi>も</kunyomi>
<description>mama</description>
<description>mother</description>
</kanji_entry>
<kanji_entry>
<ent_seq>88990071</ent_seq>
<kanji>火</kanji>
<name>火</name>
<jlpt>5</jlpt>
<level>1</level>
<onyomi>カ</onyomi>
<kunyomi>ひ</kunyomi>
<kunyomi>-び</kunyomi>
<kunyomi>ほ-</kunyomi>
<description>fire</description>
</kanji_entry>
<kanji_entry>
<ent_seq>88990072</ent_seq>
<kanji>右</kanji>
<name>右</name>
<jlpt>5</jlpt>
<level>1</level>
<onyomi>ウ</onyomi>
<onyomi>ユウ</onyomi>
<onyomi>ミ</onyomi>
<description>right</description>
</kanji_entry>
<kanji_entry>
<ent_seq>88990073</ent_seq>
<kanji>読</kanji>
<name>読</name>
<jlpt>5</jlpt>
<level>1</level>
<onyomi>ドク</onyomi>
<onyomi>トク</onyomi>
<onyomi>トウ</onyomi>
<onyomi>-ヨ.</onyomi>
<kunyomi>よ.む</kunyomi>
<description>read</description>
</kanji_entry>
<kanji_entry>
<ent_seq>88990074</ent_seq>
<kanji>友</kanji>
<name>友</name>
<jlpt>5</jlpt>
<level>1</level>
<onyomi>ユウ</onyomi>
<onyomi>ト</onyomi>
<description>friend</description>
</kanji_entry>
<kanji_entry>
<ent_seq>88990075</ent_seq>
<kanji>左</kanji>
<name>左</name>
<jlpt>5</jlpt>
<level>1</level>
<onyomi>サ</onyomi>
<onyomi>シャ</onyomi>
<onyomi>ヒダ</onyomi>
<description>left</description>
</kanji_entry>
<kanji_entry>
<ent_seq>88990076</ent_seq>
<kanji>休</kanji>
<name>休</name>
<jlpt>5</jlpt>
<level>1</level>
<onyomi>キュウ</onyomi>
<kunyomi>やす.む</kunyomi>
<kunyomi>やす.まる</kunyomi>
<kunyomi>やす.める</kunyomi>
<description>rest</description>
<description>day off</description>
<description>retire</description>
<description>sleep</description>
</kanji_entry>
<kanji_entry>
<ent_seq>88990077</ent_seq>
<kanji>父</kanji>
<name>父</name>
<jlpt>5</jlpt>
<level>1</level>
<onyomi>フ</onyomi>	
<kunyomi>ちち</kunyomi>
<description>father</description>
</kanji_entry>
<kanji_entry>
<kanji>雨</kanji>
<name>雨</name>
<jlpt>5</jlpt>
<level>1</level>
<onyomi>ウ</onyomi>
<kunyomi>あめ</kunyomi>
<kunyomi>あま-</kunyomi>
<kunyomi>-さめ</kunyomi>
<description>rain</description>
</kanji_entry>
</GKkanji>
