<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE GKvocab [
<!ELEMENT GKvocab (vocab_entry*)>

<!-- Voabu;ary Entries consist of ...  -->
<!ELEMENT vocab_entry (ent_seq, kanji, furigana, jlpt, level,  pos,  def1+, def2+, def3+, note+, tag+ )>

<!ELEMENT ent_seq (#PCDATA)>
	<!-- A unique numeric sequence number for each vocab entry -->

<!ELEMENT kanji (#PCDATA)>
	<!-- The vocabulary entry text containing kanji characters -->

<!ELEMENT furigana (#PCDATA)>
	<!-- Vocabulary entry in furigana -->

<!ELEMENT jlpt (#PCDATA)>
	<!--  JLPT Level N5, N4, N3, N2, N1, N1+ -->

<!ELEMENT level (#PCDATA)>
	<!--  Sublevel within the JLPT level -->

<!ELEMENT pos (#PCDATA)>
	<!--  Part of Speech -->

<!ELEMENT def1 (#PCDATA)>
	<!-- Main definition -->

<!ELEMENT def2 (#PCDATA)>
	<!-- Second definition -->

<!ELEMENT def3 (#PCDATA)>
	<!-- Third definition -->

<!ELEMENT notes (#PCDATA)>
	<!-- Helpful notes about hte vocabulary entry-->

<!ELEMENT tags (#PCDATA)>
	<!-- Tags to further classify the vocabulary entry -->


<!-- GKvocab created: 2019-2-20 -->
<GKvocab>

<vocab_entry>
<ent_seq>20190210000</ent_seq>
<kanji></kanji>
<furigana>あいかわらず</furigana>
<jlpt>2</jlpt>
<level>1</level>
<pos>noun</pos>
<def1>as ever</def1>
<def1>as usual</def1>
<def1>the same</def1>
<def2></def2>
<def3></def3>
<notes></notes>
<tags></tags>
</vocab_entry>

<vocab_entry>
<ent_seq>20190210001</ent_seq>
<kanji></kanji>
<furigana>アイディア</furigana>
<jlpt>2</jlpt>
<level>1</level>
<pos>noun</pos>
<def1>idea</def1>
<def2></def2>
<def3></def3>
<notes></notes>
<tags></tags>
</vocab_entry>


<vocab_entry>
<ent_seq>2019021000</ent_seq>
<kanji>遭う</kanji>	
<furigana>あう</furigana>	
<def1>to meet</def1>
<def1>to encounter (undesirable nuance)</def1>
</vocab_entry>

<vocab_entry>
<ent_seq>2019021001</ent_seq>
<kanji>扇ぐ</kanji>	
<furigana>あおぐ</furigana>	
<def1>to fan</def1>
<def1>to flap</def1>
</vocab_entry>

<vocab_entry>
<ent_seq>2019021002</ent_seq>
<kanji>青白い</kanji>	
<furigana>あおじろい</furigana>	
<def1>pale</def1>
<def1>pallid</def1>
</vocab_entry>

<vocab_entry>
<ent_seq>2019021003</ent_seq>
<kanji>明き</kanji>	
<furigana>あき</furigana>	
<def1>room</def1>
<def1>time to spare</def1>
<def1>emptiness</def1>
</vocab_entry>

<vocab_entry>
<ent_seq>2019021004</ent_seq>
<kanji>飽くまで</kanji>	
<furigana>あくまで</furigana>	
<def1>to the end</def1>
<def1>to the last</def1>
<def1>stubbornly</def1>
</vocab_entry>

<vocab_entry>
<ent_seq>2019021005</ent_seq>
<kanji>明け方</kanji>	
<furigana>あけがた</furigana>	
<def1>dawn</def1>
</vocab_entry>

<vocab_entry>
<ent_seq>2019021006</ent_seq>
<kanji>揚げる</kanji>	
<furigana>あげる</furigana>	
<def1>to lift</def1>
<def1>to fry</def1>
</vocab_entry>

<vocab_entry>
<ent_seq>2019021007</ent_seq>
<kanji>挙げる</kanji>	
<furigana>あげる</furigana>	
<def1>to raise</def1>
<def1>to fly</def1>
</vocab_entry>

<vocab_entry>
<ent_seq>2019021008</ent_seq>
<kanji>憧れる</kanji>	
<furigana>あこがれる</furigana>	
<def1>to long for</def1>
<def1>to yearn after</def1>
<def1>to admire</def1>
</vocab_entry>

<vocab_entry>
<ent_seq>2019021009</ent_seq>
<kanji>足跡</kanji>	
<furigana>あしあと</furigana>	
<def1>footprints</def1>
</vocab_entry>

<vocab_entry>
<ent_seq>2019021010</ent_seq>
<kanji>味わう</kanji>	
<furigana>あじわう</furigana>	
<def1>to taste</def1>
<def1>to savor</def1>
<def1>to relish</def1>
</vocab_entry>

<vocab_entry>
<ent_seq>2019021011</ent_seq>
<kanji>預かる</kanji>	
<furigana>あずかる</furigana>	
<def1>to keep in custody</def1>
<def1>to receive on deposit</def1>
<def1>to take charge of</def1>
</vocab_entry>

<vocab_entry>
<ent_seq>2019021012</ent_seq>
<kanji>暖まる</kanji>	
<furigana>あたたまる</furigana>	
<def1>to warm up</def1>
<def1>to get warm</def1>
</vocab_entry>

<vocab_entry>
<ent_seq>2019021013</ent_seq>
<kanji>暖める</kanji>	
<furigana>あたためる</furigana>	
<def1>to warm</def1>
<def1>to heat</def1>
</vocab_entry>

<vocab_entry>
<ent_seq>2019021014</ent_seq>
<kanji>厚かましい</kanji>	
<furigana>あつかましい</furigana>	
<def1>impudent</def1>
<def1>shameless</def1>
<def1>brazen</def1>
</vocab_entry>

<vocab_entry>
<ent_seq>2019021015</ent_seq>
<kanji>圧縮</kanji>	
<furigana>あっしゅく</furigana>	
<def1>compression</def1>
<def1>condensation</def1>
<def1>pressure</def1>
</vocab_entry>

<vocab_entry>
<ent_seq>2019021016</ent_seq>
<kanji>宛名</kanji>	
<furigana>あてな</furigana>	
<def1>address</def1>
<def1>direction</def1>
</vocab_entry>

<vocab_entry>
<ent_seq>2019021017</ent_seq>
<kanji>暴れる</kanji>	
<furigana>あばれる</furigana>	
<def1>to act violently</def1>
<def1>to rage</def1>
<def1>to struggle</def1>
<def1>to be riotous</def1>
</vocab_entry>

<vocab_entry>
<ent_seq>2019021018</ent_seq>
<kanji>脂</kanji>	
<furigana>あぶら</furigana>	
<def1>fat</def1>
<def1>tallow</def1>
<def1>lard</def1>
</vocab_entry>

<vocab_entry>
<ent_seq>2019021019</ent_seq>
<kanji>雨戸</kanji>	
<furigana>あまど</furigana>	
<def1>sliding storm door</def1>
</vocab_entry>

<vocab_entry>
<ent_seq>2019021020</ent_seq>
<kanji>甘やかす</kanji>	
<furigana>あまやかす</furigana>	
<def1>to pamper</def1>
<def1>to spoil</def1>
</vocab_entry>

<vocab_entry>
<ent_seq>2019021021</ent_seq>
<kanji>余る</kanji>	
<furigana>あまる</furigana>	
<def1>to remain</def1>
<def1>to be left over</def1>
<def1>to be in excess</def1>
<def1>to be too many</def1>
</vocab_entry>

<vocab_entry>
<ent_seq>2019021022</ent_seq>
<kanji>編物</kanji>	
<furigana>あみもの</furigana>	
<def1>knitting</def1>
<def1>web</def1>
</vocab_entry>

<vocab_entry>
<ent_seq>2019021023</ent_seq>
<kanji>編む</kanji>	
<furigana>あむ</furigana>	
<def1>to knit</def1>
</vocab_entry>

<vocab_entry>
<ent_seq>2019021024</ent_seq>
<kanji>危うい</kanji>	
<furigana>あやうい</furigana>	
<def1>dangerous</def1>
<def1>critical</def1>
<def1>grave</def1>
</vocab_entry>

<vocab_entry>
<ent_seq>2019021025</ent_seq>
<kanji>怪しい</kanji>	
<furigana>あやしい</furigana>	
<def1>suspicious</def1>
<def1>dubious</def1>
<def1>doubtful</def1>
</vocab_entry>

<vocab_entry>
<ent_seq>2019021026</ent_seq>
<kanji>荒い</kanji>	
<furigana>あらい</furigana>	
<def1>rough</def1>
<def1>rude</def1>
<def1>wild</def1>
</vocab_entry>

<vocab_entry>
<ent_seq>2019021027</ent_seq>
<kanji>粗い</kanji>	
<furigana>あらい</furigana>	
<def1>coarse</def1>
<def1>rough</def1>
</vocab_entry>

<vocab_entry>
<ent_seq>2019021028</ent_seq>
<kanji>争う</kanji>	
<furigana>あらそう</furigana>	
<def1>to dispute</def1>
<def1>to argue</def1>
<def1>to be at variance</def1>
<def1>to compete</def1>
</vocab_entry>

<vocab_entry>
<ent_seq>2019021029</ent_seq>
<kanji>改めて</kanji>	
<furigana>あらためて</furigana>	
<def1>another time</def1>
<def1>again</def1>
<def1>over again</def1>
<def1>anew</def1>
<def1>formally</def1>
</vocab_entry>

<vocab_entry>
<ent_seq>2019021030</ent_seq>
<kanji>改める</kanji>	
<furigana>あらためる</furigana>	
<def1>to change</def1>
<def1>to alter</def1>
<def1>to reform</def1>
<def1>to revise</def1>
</vocab_entry>

<vocab_entry>
<ent_seq>2019021031</ent_seq>
<kanji>著す</kanji>	
<furigana>あらわす</furigana>	
<def1>to write</def1>
<def1>to publish</def1>
</vocab_entry>

<vocab_entry>
<ent_seq>2019021032</ent_seq>
<kanji>有難い</kanji>	
<furigana>ありがたい</furigana>	
<def1>grateful</def1>
<def1>thankful</def1>
<def1>welcome</def1>
<def1>appreciated</def1>
<def1>evoking gratitude</def1>
</vocab_entry>

<vocab_entry>
<ent_seq>2019021033</ent_seq>
<kanji>在る</kanji>	
<furigana>ある</furigana>	
<def1>to live</def1>
<def1>to be</def1>
</vocab_entry>

<vocab_entry>
<ent_seq>2019021034</ent_seq>
<kanji>安易</kanji>	
<furigana>あんい</furigana>	
<def1>easy-going</def1>
</vocab_entry>

<vocab_entry>
<ent_seq>2019021035</ent_seq>
<kanji>案外</kanji>	
<furigana>あんがい</furigana>	
<def1>unexpectedly</def1>
</vocab_entry>

<vocab_entry>
<ent_seq>2019021036</ent_seq>
<kanji>言い出す</kanji>	
<furigana>いいだす</furigana>	
<def1>to start talking</def1>
<def1>to speak</def1>
<def1>to tell</def1>
<def1>to propose</def1>
<def1>to suggest</def1>
<def1>to break the ice</def1>
</vocab_entry>

<vocab_entry>
<ent_seq>2019021037</ent_seq>
<kanji>言い付ける</kanji>	
<furigana>いいつける</furigana>	
<def1>to tell</def1>
<def1>to tell on (someone)</def1>
<def1>to order</def1>
</vocab_entry>

<vocab_entry>
<ent_seq>2019021038</ent_seq>
<kanji>意義</kanji>	
<furigana>いぎ</furigana>	
<def1>meaning</def1>
<def1>significance</def1>
</vocab_entry>

<vocab_entry>
<ent_seq>2019021039</ent_seq>
<kanji>生き生き</kanji>	
<furigana>いきいき</furigana>	
<def1>vividly</def1>
<def1>lively</def1>
</vocab_entry>

<vocab_entry>
<ent_seq>2019021040</ent_seq>
<kanji>育児</kanji>	
<furigana>いくじ</furigana>	
<def1>childcare</def1>
<def1>nursing</def1>
<def1>upbringing</def1>
</vocab_entry>

<vocab_entry>
<ent_seq>2019021041</ent_seq>
<kanji>幾分</kanji>	
<furigana>いくぶん</furigana>	
<def1>somewhat</def1>
</vocab_entry>

<vocab_entry>
<ent_seq>2019021042</ent_seq>
<kanji>生け花</kanji>	
<furigana>いけばな</furigana>	
<def1>flower arrangement</def1>
</vocab_entry>

<vocab_entry>
<ent_seq>2019021043</ent_seq>
<kanji>以後</kanji>	
<furigana>いご</furigana>	
<def1>after this</def1>
<def1>from now on</def1>
<def1>hereafter</def1>
<def1>thereafter</def1>
</vocab_entry>

<vocab_entry>
<ent_seq>2019021044</ent_seq>
<kanji>以降</kanji>	
<furigana>いこう</furigana>	
<def1>on and after</def1>
<def1>hereafter</def1>
<def1>thereafter</def1>
</vocab_entry>

<vocab_entry>
<ent_seq>2019021045</ent_seq>
<kanji>勇ましい</kanji>	
<furigana>いさましい</furigana>	
<def1>brave</def1>
<def1>valiant</def1>
<def1>gallant</def1>
<def1>courageous</def1>
</vocab_entry>

<vocab_entry>
<ent_seq>2019021046</ent_seq>
<kanji>衣食住</kanji>	
<furigana>いしょくじゅう</furigana>	
<def1>necessities of life (food, clothing, etc.)</def1>
</vocab_entry>

<vocab_entry>
<ent_seq>2019021047</ent_seq>
<kanji>意地悪</kanji>	
<furigana>いじわる</furigana>	
<def1>malicious</def1>
<def1>ill-tempered</def1>
<def1>unkind</def1>
</vocab_entry>

<vocab_entry>
<ent_seq>2019021048</ent_seq>
<kanji>一応</kanji>	
<furigana>いちおう</furigana>	
<def1>once</def1>
<def1>tentatively</def1>
<def1>in outline</def1>
<def1>for the time being</def1>
</vocab_entry>

<vocab_entry>
<ent_seq>2019021049</ent_seq>
<kanji>一段と</kanji>	
<furigana>いちだんと</furigana>	
<def1>greater</def1>
<def1>more</def1>
<def1>further</def1>
<def1>still more</def1>
</vocab_entry>

<vocab_entry>
<ent_seq>2019021050</ent_seq>
<kanji>一流</kanji>	
<furigana>いちりゅう</furigana>	
<def1>first class</def1>
<def1>top grade</def1>
<def1>foremost</def1>
<def1>top-notch</def1>
</vocab_entry>

<vocab_entry>
<ent_seq>2019021051</ent_seq>
<kanji>佚</kanji>	
<furigana>いつ</furigana>	
<def1>be lost</def1>
<def1>peace</def1>
<def1>hide</def1>
<def1>mistake</def1>
<def1>beautiful</def1>
<def1>in turn</def1>
</vocab_entry>

<vocab_entry>
<ent_seq>2019021052</ent_seq>
<kanji>一昨日</kanji>	
<furigana>いっさくじつ</furigana>	
<def1>day before yesterday</def1>
</vocab_entry>

<vocab_entry>
<ent_seq>2019021053</ent_seq>
<kanji>一昨年</kanji>	
<furigana>いっさくねん</furigana>	
<def1>year before last</def1>
</vocab_entry>

<vocab_entry>
<ent_seq>2019021054</ent_seq>
<kanji>一斉</kanji>	
<furigana>いっせい</furigana>	
<def1>simultaneous</def1>
<def1>all at once</def1>
</vocab_entry>

<vocab_entry>
<ent_seq>2019021055</ent_seq>
<kanji>一旦</kanji>	
<furigana>いったん</furigana>	
<def1>once</def1>
<def1>for a moment</def1>
<def1>one morning</def1>
<def1>temporarily</def1>
</vocab_entry>

<vocab_entry>
<ent_seq>2019021056</ent_seq>
<kanji>一定</kanji>	
<furigana>いってい</furigana>	
<def1>fixed</def1>
<def1>settled</def1>
<def1>definite</def1>
</vocab_entry>

<vocab_entry>
<ent_seq>2019021057</ent_seq>
<kanji>移転</kanji>	
<furigana>いてん</furigana>	
<def1>moving</def1>
<def1>transfer</def1>
<def1>demise</def1>
</vocab_entry>

<vocab_entry>
<ent_seq>2019021058</ent_seq>
<kanji>井戸</kanji>	
<furigana>いど</furigana>	
<def1>water well</def1>
</vocab_entry>

<vocab_entry>
<ent_seq>2019021059</ent_seq>
<kanji>緯度</kanji>	
<furigana>いど</furigana>	
<def1>latitude (nav.)</def1>
</vocab_entry>

<vocab_entry>
<ent_seq>2019021060</ent_seq>
<kanji>従姉妹</kanji>	
<furigana>いとこ</furigana>	
<def1>cousin (female)</def1>
</vocab_entry>

<vocab_entry>
<ent_seq>2019021061</ent_seq>
<kanji>威張る</kanji>	
<furigana>いばる</furigana>	
<def1>to be proud</def1>
<def1>to swagger</def1>
</vocab_entry>

<vocab_entry>
<ent_seq>2019021062</ent_seq>
<kanji>嫌がる</kanji>	
<furigana>いやがる</furigana>	
<def1>to hate</def1>
<def1>to dislike</def1>
</vocab_entry>

<vocab_entry>
<ent_seq>2019021063</ent_seq>
<kanji>煎る</kanji>	
<furigana>いる</furigana>	
<def1>to parch</def1>
<def1>to fry</def1>
</vocab_entry>

<vocab_entry>
<ent_seq>2019021064</ent_seq>
<kanji>入れ物</kanji>	
<furigana>いれもの</furigana>	
<def1>container</def1>
<def1>case</def1>
<def1>receptacle</def1>
</vocab_entry>

<vocab_entry>
<ent_seq>2019021065</ent_seq>
<kanji>引力</kanji>	
<furigana>いんりょく</furigana>	
<def1>gravity</def1>
</vocab_entry>

<vocab_entry>
<ent_seq>2019021066</ent_seq>
<kanji>植木</kanji>	
<furigana>うえき</furigana>	
<def1>garden shrubs</def1>
<def1>trees</def1>
<def1>potted plant</def1>
</vocab_entry>

<vocab_entry>
<ent_seq>2019021067</ent_seq>
<kanji>飢える</kanji>	
<furigana>うえる</furigana>	
<def1>to starve</def1>
</vocab_entry>

<vocab_entry>
<ent_seq>2019021068</ent_seq>
<kanji>浮ぶ</kanji>	
<furigana>うかぶ</furigana>	
<def1>to float</def1>
<def1>to rise to surface</def1>
<def1>to come to mind</def1>
</vocab_entry>

<vocab_entry>
<ent_seq>2019021069</ent_seq>
<kanji>浮かべる</kanji>	
<furigana>うかべる</furigana>	
<def1>to float</def1>
<def1>to express</def1>
<def1>to look (sad, glad)</def1>
</vocab_entry>

<vocab_entry>
<ent_seq>2019021070</ent_seq>
<kanji>浮く</kanji>	
<furigana>うく</furigana>	
<def1>to float</def1>
<def1>to become merry</def1>
<def1>to become loose</def1>
</vocab_entry>

<vocab_entry>
<ent_seq>2019021071</ent_seq>
<kanji>承る</kanji>	
<furigana>うけたまわる</furigana>	
<def1>(hum) to hear</def1>
<def1>to be told</def1>
<def1>to know</def1>
</vocab_entry>

<vocab_entry>
<ent_seq>2019021072</ent_seq>
<kanji>受取</kanji>	
<furigana>うけとり</furigana>	
<def1>receipt</def1>
</vocab_entry>

<vocab_entry>
<ent_seq>2019021073</ent_seq>
<kanji>受け持つ</kanji>	
<furigana>うけもつ</furigana>	
<def1>to take (be in) charge of</def1>
</vocab_entry>

<vocab_entry>
<ent_seq>2019021074</ent_seq>
<kanji>薄暗い</kanji>	
<furigana>うすぐらい</furigana>	
<def1>dim</def1>
<def1>gloomy</def1>
</vocab_entry>

<vocab_entry>
<ent_seq>2019021075</ent_seq>
<kanji>薄める</kanji>	
<furigana>うすめる</furigana>	
<def1>to dilute</def1>
<def1>to water down</def1>
</vocab_entry>

<vocab_entry>
<ent_seq>2019021076</ent_seq>
<kanji>打合せ</kanji>	
<furigana>うちあわせ</furigana>	
<def1>business meeting</def1>
<def1>previous arrangement</def1>
<def1>appointment</def1>
</vocab_entry>

<vocab_entry>
<ent_seq>2019021077</ent_seq>
<kanji>打ち消す</kanji>	
<furigana>うちけす</furigana>	
<def1>to deny</def1>
<def1>to negate</def1>
<def1>to contradict</def1>
</vocab_entry>

<vocab_entry>
<ent_seq>2019021078</ent_seq>
<kanji>討つ</kanji>	
<furigana>うつ</furigana>	
<def1>to attack</def1>
<def1>to avenge</def1>
</vocab_entry>

<vocab_entry>
<ent_seq>2019021079</ent_seq>
<kanji>映す</kanji>	
<furigana>うつす</furigana>	
<def1>to project</def1>
<def1>to reflect</def1>
<def1>to cast (shadow)</def1>
</vocab_entry>

<vocab_entry>
<ent_seq>2019021080</ent_seq>
<kanji>写る</kanji>	
<furigana>うつる</furigana>	
<def1>to be photographed</def1>
<def1>to be projected</def1>
</vocab_entry>

<vocab_entry>
<ent_seq>2019021081</ent_seq>
<kanji>映る</kanji>	
<furigana>うつる</furigana>	
<def1>to be reflected</def1>
<def1>to harmonize with</def1>
<def1>to come out (photo)</def1>
</vocab_entry>

<vocab_entry>
<ent_seq>2019021082</ent_seq>
<kanji>有無</kanji>	
<furigana>うむ</furigana>	
<def1>yes or no</def1>
<def1>existence</def1>
<def1>flag indicator (comp)</def1>
<def1>presence or absence marker</def1>
</vocab_entry>

<vocab_entry>
<ent_seq>2019021083</ent_seq>
<kanji>埋める</kanji>	
<furigana>うめる</furigana>	
<def1>to bury</def1>
<def1>to fill up</def1>
<def1>to fill (a seat, a vacant position)</def1>
</vocab_entry>

<vocab_entry>
<ent_seq>2019021084</ent_seq>
<kanji>敬う</kanji>	
<furigana>うやまう</furigana>	
<def1>to show respect</def1>
<def1>to honour</def1>
</vocab_entry>

<vocab_entry>
<ent_seq>2019021085</ent_seq>
<kanji>裏返す</kanji>	
<furigana>うらがえす</furigana>	
<def1>to turn inside out</def1>
<def1>to turn (something) over</def1>
</vocab_entry>

<vocab_entry>
<ent_seq>2019021086</ent_seq>
<kanji>裏口</kanji>	
<furigana>うらぐち</furigana>	
<def1>backdoor</def1>
<def1>rear entrance</def1>
</vocab_entry>

<vocab_entry>
<ent_seq>2019021087</ent_seq>
<kanji>占う</kanji>	
<furigana>うらなう</furigana>	
<def1>to forecast</def1>
<def1>to predict</def1>
</vocab_entry>

<vocab_entry>
<ent_seq>2019021088</ent_seq>
<kanji>恨み</kanji>	
<furigana>うらみ</furigana>	
<def1>resentment</def1>
</vocab_entry>

<vocab_entry>
<ent_seq>2019021089</ent_seq>
<kanji>恨む</kanji>	
<furigana>うらむ</furigana>	
<def1>to curse</def1>
<def1>to feel bitter</def1>
</vocab_entry>

<vocab_entry>
<ent_seq>2019021090</ent_seq>
<kanji>羨ましい</kanji>	
<furigana>うらやましい</furigana>	
<def1>envious</def1>
<def1>enviable</def1>
</vocab_entry>

<vocab_entry>
<ent_seq>2019021091</ent_seq>
<kanji>羨む</kanji>	
<furigana>うらやむ</furigana>	
<def1>to envy</def1>
</vocab_entry>

<vocab_entry>
<ent_seq>2019021092</ent_seq>
<kanji>売上</kanji>	
<furigana>うりあげ</furigana>	
<def1>amount sold</def1>
<def1>proceeds</def1>
</vocab_entry>

<vocab_entry>
<ent_seq>2019021093</ent_seq>
<kanji>売り切れ</kanji>	
<furigana>うりきれ</furigana>	
<def1>sold-out</def1>
</vocab_entry>

<vocab_entry>
<ent_seq>2019021094</ent_seq>
<kanji>売り切れる</kanji>	
<furigana>うりきれる</furigana>	
<def1>to be sold out</def1>
</vocab_entry>

<vocab_entry>
<ent_seq>2019021095</ent_seq>
<kanji>売行き</kanji>	
<furigana>うれゆき</furigana>	
<def1>sales</def1>
</vocab_entry>

<vocab_entry>
<ent_seq>2019021096</ent_seq>
<kanji>運河</kanji>	
<furigana>うんが</furigana>	
<def1>canal</def1>
<def1>waterway</def1>
</vocab_entry>

<vocab_entry>
<ent_seq>2019021097</ent_seq>
<kanji>英文</kanji>	
<furigana>えいぶん</furigana>	
<def1>sentence in English</def1>
</vocab_entry>

<vocab_entry>
<ent_seq>2019021098</ent_seq>
<kanji>英和</kanji>	
<furigana>えいわ</furigana>	
<def1>English-Japanese (e.g. dictionary)</def1>
</vocab_entry>

<vocab_entry>
<ent_seq>2019021099</ent_seq>
<kanji>液体</kanji>	
<furigana>えきたい</furigana>	
<def1>liquid</def1>
<def1>fluid</def1>
</vocab_entry>

<vocab_entry>
<ent_seq>2019021100</ent_seq>
<kanji>絵の具</kanji>	
<furigana>えのぐ</furigana>	
<def1>colors</def1>
<def1>paints</def1>
</vocab_entry>

<vocab_entry>
<ent_seq>2019021101</ent_seq>
<kanji>偉い</kanji>	
<furigana>えらい</furigana>	
<def1>great</def1>
<def1>celebrated</def1>
<def1>eminent</def1>
<def1>terrible</def1>
<def1>awful</def1>
<def1>famous</def1>
<def1>remarkable</def1>
<def1>excellent</def1>
</vocab_entry>

<vocab_entry>
<ent_seq>2019021102</ent_seq>
<kanji>宴会</kanji>	
<furigana>えんかい</furigana>	
<def1>party</def1>
<def1>banquet</def1>
</vocab_entry>

<vocab_entry>
<ent_seq>2019021103</ent_seq>
<kanji>園芸</kanji>	
<furigana>えんげい</furigana>	
<def1>horticulture</def1>
<def1>gardening</def1>
</vocab_entry>

<vocab_entry>
<ent_seq>2019021104</ent_seq>
<kanji>演劇</kanji>	
<furigana>えんげき</furigana>	
<def1>play (theatrical)</def1>
</vocab_entry>

<vocab_entry>
<ent_seq>2019021105</ent_seq>
<kanji>円周</kanji>	
<furigana>えんしゅう</furigana>	
<def1>circumference</def1>
</vocab_entry>

<vocab_entry>
<ent_seq>2019021106</ent_seq>
<kanji>遠足</kanji>	
<furigana>えんそく</furigana>	
<def1>trip</def1>
<def1>hike</def1>
<def1>picnic</def1>
</vocab_entry>

<vocab_entry>
<ent_seq>2019021107</ent_seq>
<kanji>延長</kanji>	
<furigana>えんちょう</furigana>	
<def1>extension</def1>
<def1>elongation</def1>
<def1>prolongation</def1>
<def1>lengthening</def1>
</vocab_entry>

<vocab_entry>
<ent_seq>2019021108</ent_seq>
<kanji>煙突</kanji>	
<furigana>えんとつ</furigana>	
<def1>chimney</def1>
</vocab_entry>

<vocab_entry>
<ent_seq>2019021109</ent_seq>
<kanji>追い掛ける</kanji>	
<furigana>おいかける</furigana>	
<def1>to chase or run after someone</def1>
<def1>to run down</def1>
<def1>to pursue</def1>
</vocab_entry>

<vocab_entry>
<ent_seq>2019021110</ent_seq>
<kanji>追い越す</kanji>	
<furigana>おいこす</furigana>	
<def1>to pass (e.g. car)</def1>
<def1>to outdistance</def1>
<def1>to outstrip</def1>
</vocab_entry>

<vocab_entry>
<ent_seq>2019021111</ent_seq>
<kanji>応援</kanji>	
<furigana>おうえん</furigana>	
<def1>aid</def1>
<def1>assistance</def1>
<def1>help</def1>
<def1>reinforcement</def1>
</vocab_entry>

<vocab_entry>
<ent_seq>2019021112</ent_seq>
<kanji>王女</kanji>	
<furigana>おうじょ</furigana>	
<def1>princess</def1>
</vocab_entry>

<vocab_entry>
<ent_seq>2019021113</ent_seq>
<kanji>応ずる</kanji>	
<furigana>おうずる</furigana>	
<def1>to answer</def1>
<def1>to respond</def1>
<def1>to meet</def1>
<def1>to satisfy</def1>
<def1>to accept</def1>
</vocab_entry>

<vocab_entry>
<ent_seq>2019021114</ent_seq>
<kanji>応接</kanji>	
<furigana>おうせつ</furigana>	
<def1>reception</def1>
</vocab_entry>

<vocab_entry>
<ent_seq>2019021115</ent_seq>
<kanji>応対</kanji>	
<furigana>おうたい</furigana>	
<def1>receiving</def1>
<def1>dealing with</def1>
</vocab_entry>

<vocab_entry>
<ent_seq>2019021116</ent_seq>
<kanji>往復</kanji>	
<furigana>おうふく</furigana>	
<def1>(col) round trip</def1>
<def1>coming and going</def1>
<def1>return ticket</def1>
</vocab_entry>

<vocab_entry>
<ent_seq>2019021117</ent_seq>
<kanji>欧米</kanji>	
<furigana>おうべい</furigana>	
<def1>Europe and America</def1>
<def1>the West</def1>
</vocab_entry>

<vocab_entry>
<ent_seq>2019021118</ent_seq>
<kanji>応用</kanji>	
<furigana>おうよう</furigana>	
<def1>application</def1>
<def1>put to practical use</def1>
</vocab_entry>

<vocab_entry>
<ent_seq>2019021119</ent_seq>
<kanji>大通り</kanji>	
<furigana>おおどおり</furigana>	
<def1>main street</def1>
</vocab_entry>

<vocab_entry>
<ent_seq>2019021120</ent_seq>
<kanji>大凡</kanji>	
<furigana>おおよそ</furigana>	
<def1>about</def1>
<def1>roughly</def1>
<def1>as a rule</def1>
<def1>approximately</def1>
</vocab_entry>

<vocab_entry>
<ent_seq>2019021121</ent_seq>
<kanji>お帰り</kanji>	
<furigana>おかえり</furigana>	
<def1>return</def1>
<def1>welcome</def1>
</vocab_entry>

<vocab_entry>
<ent_seq>2019021122</ent_seq>
<kanji>拝む</kanji>	
<furigana>おがむ</furigana>	
<def1>to worship</def1>
<def1>to beg</def1>
<def1>to make a supplication</def1>
</vocab_entry>

<vocab_entry>
<ent_seq>2019021123</ent_seq>
<kanji>お代わり</kanji>	
<furigana>おかわり</furigana>	
<def1>second helping</def1>
<def1>another cup</def1>
</vocab_entry>

<vocab_entry>
<ent_seq>2019021124</ent_seq>
<kanji>補う</kanji>	
<furigana>おぎなう</furigana>	
<def1>to compensate for</def1>
</vocab_entry>

<vocab_entry>
<ent_seq>2019021125</ent_seq>
<kanji>屋外</kanji>	
<furigana>おくがい</furigana>	
<def1>outdoors</def1>
</vocab_entry>

<vocab_entry>
<ent_seq>2019021126</ent_seq>
<kanji>送り仮名</kanji>	
<furigana>おくりがな</furigana>	
<def1>part of word written in kana</def1>
</vocab_entry>

<vocab_entry>
<ent_seq>2019021127</ent_seq>
<kanji>怠る</kanji>	
<furigana>おこたる</furigana>	
<def1>to neglect</def1>
<def1>to be off guard</def1>
<def1>to be feeling better</def1>
</vocab_entry>

<vocab_entry>
<ent_seq>2019021128</ent_seq>
<kanji>押える</kanji>	
<furigana>おさえる</furigana>	
<def1>to stop</def1>
<def1>to restrain</def1>
<def1>to seize</def1>
<def1>to repress</def1>
<def1>to suppress</def1>
<def1>to press down</def1>
</vocab_entry>

<vocab_entry>
<ent_seq>2019021129</ent_seq>
<kanji>納める</kanji>	
<furigana>おさめる</furigana>	
<def1>to obtain</def1>
<def1>to reap</def1>
<def1>to pay</def1>
<def1>to supply</def1>
<def1>to accept</def1>
</vocab_entry>

<vocab_entry>
<ent_seq>2019021130</ent_seq>
<kanji>惜しい</kanji>	
<furigana>おしい</furigana>	
<def1>regrettable</def1>
<def1>disappointing</def1>
<def1>precious</def1>
</vocab_entry>

<vocab_entry>
<ent_seq>2019021131</ent_seq>
<kanji>御辞儀</kanji>	
<furigana>おじぎ</furigana>	
<def1>bow</def1>
</vocab_entry>

<vocab_entry>
<ent_seq>2019021132</ent_seq>
<kanji>伯父さん</kanji>	
<furigana>おじさん</furigana>	
<def1>middle-aged gentleman</def1>
<def1>uncle</def1>
</vocab_entry>

<vocab_entry>
<ent_seq>2019021133</ent_seq>
<kanji>小父さん</kanji>	
<furigana>おじさん</furigana>	
<def1>middle-aged gentleman</def1>
<def1>uncle</def1>
</vocab_entry>

<vocab_entry>
<ent_seq>2019021134</ent_seq>
<kanji>叔父さん</kanji>	
<furigana>おじさん</furigana>	
<def1>middle-aged gentleman</def1>
<def1>uncle</def1>
</vocab_entry>

<vocab_entry>
<ent_seq>2019021135</ent_seq>
<kanji>教わる</kanji>	
<furigana>おそわる</furigana>	
<def1>to be taught</def1>
</vocab_entry>

<vocab_entry>
<ent_seq>2019021136</ent_seq>
<kanji>落着く</kanji>	
<furigana>おちつく</furigana>	
<def1>to calm down</def1>
<def1>to settle down</def1>
</vocab_entry>

<vocab_entry>
<ent_seq>2019021137</ent_seq>
<kanji>御手洗</kanji>	
<furigana>おてあらい</furigana>	
<def1>font of purifying water placed at entrance of shrine</def1>
</vocab_entry>

<vocab_entry>
<ent_seq>2019021138</ent_seq>
<kanji>お手伝いさん</kanji>	
<furigana>おてつだいさん</furigana>	
<def1>maid</def1>
</vocab_entry>

<vocab_entry>
<ent_seq>2019021139</ent_seq>
<kanji>落し物</kanji>	
<furigana>おとしもの</furigana>	
<def1>lost property</def1>
</vocab_entry>

<vocab_entry>
<ent_seq>2019021140</ent_seq>
<kanji>驚かす</kanji>	
<furigana>おどろかす</furigana>	
<def1>to surprise</def1>
<def1>to frighten</def1>
<def1>to create a stir</def1>
</vocab_entry>

<vocab_entry>
<ent_seq>2019021141</ent_seq>
<kanji>各々</kanji>	
<furigana>おのおの</furigana>	
<def1>each</def1>
<def1>every</def1>
<def1>either</def1>
<def1>respectively</def1>
<def1>severally</def1>
</vocab_entry>

<vocab_entry>
<ent_seq>2019021142</ent_seq>
<kanji>伯母さん</kanji>	
<furigana>おばさん</furigana>	
<def1>(hon) aunt</def1>
</vocab_entry>

<vocab_entry>
<ent_seq>2019021143</ent_seq>
<kanji>お参り</kanji>	
<furigana>おまいり</furigana>	
<def1>worship</def1>
<def1>shrine visit</def1>
</vocab_entry>

<vocab_entry>
<ent_seq>2019021144</ent_seq>
<kanji>思い掛けない</kanji>	
<furigana>おもいがけない</furigana>	
<def1>unexpected</def1>
<def1>casual</def1>
</vocab_entry>

<vocab_entry>
<ent_seq>2019021145</ent_seq>
<kanji>思い込む</kanji>	
<furigana>おもいこむ</furigana>	
<def1>to be under impression that</def1>
<def1>to be convinced that</def1>
</vocab_entry>

<vocab_entry>
<ent_seq>2019021146</ent_seq>
<kanji>思い付く</kanji>	
<furigana>おもいつく</furigana>	
<def1>to think of</def1>
<def1>to hit upon</def1>
</vocab_entry>

<vocab_entry>
<ent_seq>2019021147</ent_seq>
<kanji>重たい</kanji>	
<furigana>おもたい</furigana>	
<def1>heavy</def1>
<def1>massive</def1>
<def1>serious</def1>
</vocab_entry>

<vocab_entry>
<ent_seq>2019021148</ent_seq>
<kanji>親指</kanji>	
<furigana>おやゆび</furigana>	
<def1>thumb</def1>
</vocab_entry>

<vocab_entry>
<ent_seq>2019021149</ent_seq>
<kanji>卸す</kanji>	
<furigana>おろす</furigana>	
<def1>to sell wholesale</def1>
<def1>grated (vegetables)</def1>
</vocab_entry>

<vocab_entry>
<ent_seq>2019021150</ent_seq>
<kanji>恩恵</kanji>	
<furigana>おんけい</furigana>	
<def1>grace</def1>
<def1>favor</def1>
<def1>blessing</def1>
<def1>benefit</def1>
</vocab_entry>

<vocab_entry>
<ent_seq>2019021151</ent_seq>
<kanji>温室</kanji>	
<furigana>おんしつ</furigana>	
<def1>greenhouse</def1>
</vocab_entry>

<vocab_entry>
<ent_seq>2019021152</ent_seq>
<kanji>温泉</kanji>	
<furigana>おんせん</furigana>	
<def1>spa</def1>
<def1>hot spring</def1>
<def1>onsen</def1>
</vocab_entry>

<vocab_entry>
<ent_seq>2019021153</ent_seq>
<kanji>温帯</kanji>	
<furigana>おんたい</furigana>	
<def1>temperate zone</def1>
</vocab_entry>

<vocab_entry>
<ent_seq>2019021154</ent_seq>
<kanji>御中</kanji>	
<furigana>おんちゅう</furigana>	
<def1>and Company</def1>
<def1>Messrs.</def1>
</vocab_entry>

<vocab_entry>
<ent_seq>2019021155</ent_seq>
<kanji>女の人</kanji>	
<furigana>おんなのひと</furigana>	
<def1>woman</def1>
</vocab_entry>

<vocab_entry>
<ent_seq>2019021156</ent_seq>
<kanji>蚊</kanji>	
<furigana>か</furigana>	
<def1>mosquito</def1>
</vocab_entry>

<vocab_entry>
<ent_seq>2019021157</ent_seq>
<kanji>貝</kanji>	
<furigana>かい</furigana>	
<def1>shell</def1>
<def1>shellfish</def1>
</vocab_entry>

<vocab_entry>
<ent_seq>2019021158</ent_seq>
<kanji>開会</kanji>	
<furigana>かいかい</furigana>	
<def1>opening of a meeting</def1>
</vocab_entry>

<vocab_entry>
<ent_seq>2019021159</ent_seq>
<kanji>会館</kanji>	
<furigana>かいかん</furigana>	
<def1>meeting hall</def1>
<def1>assembly hall</def1>
</vocab_entry>

<vocab_entry>
<ent_seq>2019021160</ent_seq>
<kanji>改札</kanji>	
<furigana>かいさつ</furigana>	
<def1>examination of tickets</def1>
</vocab_entry>

<vocab_entry>
<ent_seq>2019021161</ent_seq>
<kanji>解散</kanji>	
<furigana>かいさん</furigana>	
<def1>breakup</def1>
<def1>dissolution</def1>
</vocab_entry>

<vocab_entry>
<ent_seq>2019021162</ent_seq>
<kanji>海水浴</kanji>	
<furigana>かいすいよく</furigana>	
<def1>sea bathing</def1>
<def1>seawater bath</def1>
</vocab_entry>

<vocab_entry>
<ent_seq>2019021163</ent_seq>
<kanji>回数</kanji>	
<furigana>かいすう</furigana>	
<def1>number of times</def1>
<def1>frequency</def1>
</vocab_entry>

<vocab_entry>
<ent_seq>2019021164</ent_seq>
<kanji>回数券</kanji>	
<furigana>かいすうけん</furigana>	
<def1>book of tickets</def1>
</vocab_entry>

<vocab_entry>
<ent_seq>2019021165</ent_seq>
<kanji>改正</kanji>	
<furigana>かいせい</furigana>	
<def1>revision</def1>
<def1>amendment</def1>
<def1>alteration</def1>
</vocab_entry>

<vocab_entry>
<ent_seq>2019021166</ent_seq>
<kanji>快晴</kanji>	
<furigana>かいせい</furigana>	
<def1>good weather</def1>
</vocab_entry>

<vocab_entry>
<ent_seq>2019021167</ent_seq>
<kanji>解説</kanji>	
<furigana>かいせつ</furigana>	
<def1>explanation</def1>
<def1>commentary</def1>
</vocab_entry>

<vocab_entry>
<ent_seq>2019021168</ent_seq>
<kanji>開通</kanji>	
<furigana>かいつう</furigana>	
<def1>opening</def1>
<def1>open</def1>
</vocab_entry>

<vocab_entry>
<ent_seq>2019021169</ent_seq>
<kanji>回転</kanji>	
<furigana>かいてん</furigana>	
<def1>rotation</def1>
<def1>revolution</def1>
<def1>turning</def1>
</vocab_entry>

<vocab_entry>
<ent_seq>2019021170</ent_seq>
<kanji>解答</kanji>	
<furigana>かいとう</furigana>	
<def1>answer</def1>
<def1>solution</def1>
</vocab_entry>

<vocab_entry>
<ent_seq>2019021171</ent_seq>
<kanji>回答</kanji>	
<furigana>かいとう</furigana>	
<def1>reply</def1>
<def1>answer</def1>
</vocab_entry>

<vocab_entry>
<ent_seq>2019021172</ent_seq>
<kanji>外部</kanji>	
<furigana>がいぶ</furigana>	
<def1>the outside</def1>
<def1>external</def1>
</vocab_entry>

<vocab_entry>
<ent_seq>2019021173</ent_seq>
<kanji>解放</kanji>	
<furigana>かいほう</furigana>	
<def1>release</def1>
<def1>liberation</def1>
<def1>emancipation</def1>
</vocab_entry>

<vocab_entry>
<ent_seq>2019021174</ent_seq>
<kanji>開放</kanji>	